### PR TITLE
Add html skeleton

### PR DESCRIPTION
**Pull request by andrewnelp**
//just a test

### CODE REVIEW

**Comment by andrewnelp** [comment]
test again

**Comment by sodastereo87** [comment]
hey

**Comment by sodastereo87** [comment]
background-color: rgb(118, 143, 143);
        }

        h2 {
            text-align: center;
        }

        .card-body a {
            word-break: break-all;
        }

        .articleHeadline {
            line-height: 1.5;
        }

        #Submit {
            float: right;
            background-color: black;
            color: white;
        }

**Comment by sodastereo87** [comment]
background-color: rgb(118, 143, 143);
        }

        h2 {
            text-align: center;
        }

        .card-body a {
            word-break: break-all;
        }

        .articleHeadline {
            line-height: 1.5;
        }

        #Submit {
            float: right;
            background-color: black;
            color: white;
        }

**Pull request closed without merging**
